--------------------------------------------------------
--  文件已创建 - 星期三-二月-24-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BUILDINGINFO
--------------------------------------------------------

  CREATE TABLE "MIANYANG"."BUILDINGINFO" 
   (	"B_ID" NUMBER(38,0), 
	"NAME" VARCHAR2(30 BYTE), 
	"OFFICE" VARCHAR2(30 BYTE), 
	"LOCATION" VARCHAR2(30 BYTE), 
	"LOCATION_LAT" BINARY_FLOAT, 
	"LOCATION_LNG" BINARY_FLOAT, 
	"MANAGER" VARCHAR2(30 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into MIANYANG.BUILDINGINFO
SET DEFINE OFF;
Insert into MIANYANG.BUILDINGINFO (B_ID,NAME,OFFICE,LOCATION,LOCATION_LAT,LOCATION_LNG,MANAGER) values (6,'亭子2','亭子2','xxxx','34.98567','104.49568','周银行');
Insert into MIANYANG.BUILDINGINFO (B_ID,NAME,OFFICE,LOCATION,LOCATION_LAT,LOCATION_LNG,MANAGER) values (7,'亭子3','亭子3','xxxx','34.98567','104.49568','周银行');
Insert into MIANYANG.BUILDINGINFO (B_ID,NAME,OFFICE,LOCATION,LOCATION_LAT,LOCATION_LNG,MANAGER) values (8,'207楼C','207','xxx','34.4747','104.49568','穆隆');
Insert into MIANYANG.BUILDINGINFO (B_ID,NAME,OFFICE,LOCATION,LOCATION_LAT,LOCATION_LNG,MANAGER) values (9,'201','201','xxx','34.4747','104.49568','穆隆');
Insert into MIANYANG.BUILDINGINFO (B_ID,NAME,OFFICE,LOCATION,LOCATION_LAT,LOCATION_LNG,MANAGER) values (10,'检测车','检测车','xxx','34.4747','104.49568','周银行');
Insert into MIANYANG.BUILDINGINFO (B_ID,NAME,OFFICE,LOCATION,LOCATION_LAT,LOCATION_LNG,MANAGER) values (11,'气象塔','气象塔','xxx','34.4747','104.49568','周银行');
Insert into MIANYANG.BUILDINGINFO (B_ID,NAME,OFFICE,LOCATION,LOCATION_LAT,LOCATION_LNG,MANAGER) values (1,'207楼','207','xxx','34.4747','104.49568','穆隆');
Insert into MIANYANG.BUILDINGINFO (B_ID,NAME,OFFICE,LOCATION,LOCATION_LAT,LOCATION_LNG,MANAGER) values (2,'208楼','208','xxx','34.94569','104.89497','穆隆');
Insert into MIANYANG.BUILDINGINFO (B_ID,NAME,OFFICE,LOCATION,LOCATION_LAT,LOCATION_LNG,MANAGER) values (3,'2115楼','2115','xxx','34.3969','104.94867','周银行');
Insert into MIANYANG.BUILDINGINFO (B_ID,NAME,OFFICE,LOCATION,LOCATION_LAT,LOCATION_LNG,MANAGER) values (4,'209','209','xxxx','34.907','104.6907','陈华');
Insert into MIANYANG.BUILDINGINFO (B_ID,NAME,OFFICE,LOCATION,LOCATION_LAT,LOCATION_LNG,MANAGER) values (5,'亭子','亭子','xxxx','34.98567','104.4987','周银行');
--------------------------------------------------------
--  DDL for Index BUILDINGINFO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MIANYANG"."BUILDINGINFO_PK" ON "MIANYANG"."BUILDINGINFO" ("B_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BUILDINGINFO
--------------------------------------------------------

  ALTER TABLE "MIANYANG"."BUILDINGINFO" ADD CONSTRAINT "BUILDINGINFO_PK" PRIMARY KEY ("B_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "MIANYANG"."BUILDINGINFO" MODIFY ("B_ID" NOT NULL ENABLE);
