--------------------------------------------------------
--  文件已创建 - 星期三-二月-24-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CABINFO
--------------------------------------------------------

  CREATE TABLE "MIANYANG"."CABINFO" 
   (	"C_ID" NUMBER(38,0), 
	"BUILDINGID" NUMBER(38,0), 
	"NAME" VARCHAR2(30 BYTE), 
	"OFFICE" VARCHAR2(30 BYTE), 
	"HOME" VARCHAR2(50 BYTE), 
	"IP" VARCHAR2(20 BYTE), 
	"PORT" VARCHAR2(8 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into MIANYANG.CABINFO
SET DEFINE OFF;
Insert into MIANYANG.CABINFO (C_ID,BUILDINGID,NAME,OFFICE,HOME,IP,PORT) values (2,2,'氚在线监测系统','208','402','192.168.1.222','0201');
Insert into MIANYANG.CABINFO (C_ID,BUILDINGID,NAME,OFFICE,HOME,IP,PORT) values (3,2,'氚在线监测系统2','208','403','192.168.1.111','0201');
Insert into MIANYANG.CABINFO (C_ID,BUILDINGID,NAME,OFFICE,HOME,IP,PORT) values (4,2,'氚在线监测系统3','208','404','192.168.1.55','0201');
--------------------------------------------------------
--  DDL for Index CABINFO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MIANYANG"."CABINFO_PK" ON "MIANYANG"."CABINFO" ("C_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CABINFO
--------------------------------------------------------

  ALTER TABLE "MIANYANG"."CABINFO" ADD CONSTRAINT "CABINFO_PK" PRIMARY KEY ("C_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "MIANYANG"."CABINFO" MODIFY ("C_ID" NOT NULL ENABLE);
