--------------------------------------------------------
--  文件已创建 - 星期三-二月-24-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DEVICEDATA_1
--------------------------------------------------------

  CREATE TABLE "MIANYANG"."DEVICEDATA_1" 
   (	"DD_ID" NUMBER(38,0), 
	"DEVID" NUMBER(38,0), 
	"DATATIME" VARCHAR2(25 BYTE), 
	"NOWVALUE" BINARY_FLOAT, 
	"ARG1" BINARY_FLOAT, 
	"ARG2" BINARY_FLOAT, 
	"ARG3" BINARY_FLOAT, 
	"ARG4" BINARY_FLOAT, 
	"ARG5" BINARY_FLOAT, 
	"ARG6" BINARY_FLOAT, 
	"ARG7" BINARY_FLOAT, 
	"ARG8" BINARY_FLOAT, 
	"UNITS" VARCHAR2(200 BYTE), 
	"SAFESTATE" VARCHAR2(10 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into MIANYANG.DEVICEDATA_1
SET DEFINE OFF;
Insert into MIANYANG.DEVICEDATA_1 (DD_ID,DEVID,DATATIME,NOWVALUE,ARG1,ARG2,ARG3,ARG4,ARG5,ARG6,ARG7,ARG8,UNITS,SAFESTATE) values (1,5,'2016-2-24 16-10-23','9000.0',null,null,null,null,null,null,null,null,'Bg/m^3','Normal');
Insert into MIANYANG.DEVICEDATA_1 (DD_ID,DEVID,DATATIME,NOWVALUE,ARG1,ARG2,ARG3,ARG4,ARG5,ARG6,ARG7,ARG8,UNITS,SAFESTATE) values (2,10,'2016-2-24 16-11-20','9100.0','220.0',null,null,null,null,null,null,null,'Bg/m^3,V','Normal');
--------------------------------------------------------
--  DDL for Index PK_DEVICEDATA_1
--------------------------------------------------------

  CREATE UNIQUE INDEX "MIANYANG"."PK_DEVICEDATA_1" ON "MIANYANG"."DEVICEDATA_1" ("DD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table DEVICEDATA_1
--------------------------------------------------------

  ALTER TABLE "MIANYANG"."DEVICEDATA_1" ADD CONSTRAINT "PK_DEVICEDATA_1" PRIMARY KEY ("DD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "MIANYANG"."DEVICEDATA_1" MODIFY ("DD_ID" NOT NULL ENABLE);
